# Generated by Django 5.0.6 on 2024-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_payment_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
