# Generated by Django 5.0.6 on 2024-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
