# Generated by Django 5.0.6 on 2024-06-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_banner_image_alter_payments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Dancers',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Musicians',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
