# Generated by Django 5.0.6 on 2024-06-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_gallery_dancers_remove_gallery_musicians_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Banner',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='Eventurl',
            field=models.URLField(max_length=50),
        ),
    ]
