# Generated by Django 5.0.6 on 2024-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_events_banner_alter_events_eventurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Imp',
            field=models.CharField(default='Imp', max_length=10),
        ),
    ]
