# Generated by Django 5.0.6 on 2024-06-13 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_events_imp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='subscribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
