# Generated by Django 5.0.6 on 2024-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_subscribe_subscribed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Imp',
            field=models.CharField(default='Not', max_length=10),
        ),
    ]
