# Generated by Django 5.0.6 on 2024-06-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_events_imp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='Email',
            new_name='Email_address',
        ),
    ]
