# Generated by Django 5.0.6 on 2024-06-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_email_subscribe_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='Email_address',
            new_name='email',
        ),
    ]
