# Generated by Django 5.0.6 on 2024-06-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_aboutevent_events_aboutevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Aboutevent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='Category',
            field=models.CharField(blank=True, default='dance', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='Desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='End_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='End_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Eventurl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Imp',
            field=models.CharField(blank=True, default='Not', max_length=10),
        ),
        migrations.AlterField(
            model_name='events',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Venue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
