# Generated by Django 5.0.6 on 2024-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_events_aboutevent_alter_events_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
