# Generated by Django 5.0.6 on 2024-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_feedback_delete_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'Blogs',
            },
        ),
    ]
