# Generated by Django 5.0.6 on 2024-07-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_blogs_date_alter_feedback_name_alter_feedback_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='Image',
        ),
    ]
